import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#C1FF00]">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
